version: '3.8'
services:

  # Mongo
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data_container:/data/

  # Backend
  personal-stock-screener:
    # env_file:
    #   - ./.private/api-keys.env "Another way to insert env variables" 
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/personal-stock-screener
    command: npm start
    working_dir: /usr/src/personal-stock-screener
    ports:
      - "3001:3001"
    environment:
      REDIS_URI: redis://redis:6379
      MONGO_URI: mongodb://mongodb:27017
    # Heads up! Docker has updated this feature and now you don't need to define the links property in order for things to work - https://docs.docker.com/compose/networking/
    # links:
    #   - postgres
    #   - redis

volumes:
  mongodb_data_container:
  redis_data_container: